var Skill = {
    ACROBATICS:       {name: 'Acrobatics',       shortName:  'acrobatics',      governingAttribute:  Attribute.DEXTERITY,    requiresTraining:  false},
    APPRAISE:         {name: 'Appraise',         shortName:  'appraise',        governingAttribute:  Attribute.INTELLIGENCE, requiresTraining:  false},
    BLUFF:            {name: 'Bluff',            shortName:  'bluff',           governingAttribute:  Attribute.CHARISMA,     requiresTraining:  false},
    CLIMB:            {name: 'Climb',            shortName:  'climb',           governingAttribute:  Attribute.STRENGTH,     requiresTraining:  false},
    CRAFT:            {name: 'Craft',            shortName:  'craft',           governingAttribute:  Attribute.INTELLIGENCE, requiresTraining:  false},
    DIPLOMACY:        {name: 'Diplomacy',        shortName:  'diplomacy',       governingAttribute:  Attribute.CHARISMA,     requiresTraining:  false},
    DISABLE_DEVICE:   {name: 'Disable Device',   shortName:  'disableDevice',   governingAttribute:  Attribute.DEXTERITY,    requiresTraining:  true},
    DISGUISE:         {name: 'Disguise',         shortName:  'disguise',        governingAttribute:  Attribute.CHARISMA,     requiresTraining:  false},
    ESCAPE_ARTIST:    {name: 'Escape Artist',    shortName:  'escapeArtist',    governingAttribute:  Attribute.DEXTERITY,    requiresTraining:  false},
    FLY:              {name: 'Fly',              shortName:  'fly',             governingAttribute:  Attribute.DEXTERITY,    requiresTraining:  false},
    HANDLE_ANIMAL:    {name: 'Handle Animal',    shortName:  'handleAnimal',    governingAttribute:  Attribute.CHARISMA,     requiresTraining:  true},
    HEAL:             {name: 'Heal',             shortName:  'heal',            governingAttribute:  Attribute.WISDOM,       requiresTraining:  false},
    INTIMIDATE:       {name: 'Intimidate',       shortName:  'intimidate',      governingAttribute:  Attribute.CHARISMA,     requiresTraining:  false},
    KN_ARCANA:        {name: 'Kn Arcana',        shortName:  'knArcana',        governingAttribute:  Attribute.INTELLIGENCE, requiresTraining:  true},
    KN_DUNGEONEERING: {name: 'Kn Dungeoneering', shortName:  'knDungeoneering', governingAttribute:  Attribute.INTELLIGENCE, requiresTraining:  true},
    KN_ENGINEERING:   {name: 'Kn Engineering',   shortName:  'knEngineering',   governingAttribute:  Attribute.INTELLIGENCE, requiresTraining:  true},
    KN_GEOGRAPHY:     {name: 'Kn Geography',     shortName:  'knGeography',     governingAttribute:  Attribute.INTELLIGENCE, requiresTraining:  true},
    KN_HISTORY:       {name: 'Kn History',       shortName:  'knHistory',       governingAttribute:  Attribute.INTELLIGENCE, requiresTraining:  true},
    KN_LOCAL:         {name: 'Kn Local',         shortName:  'knLocal',         governingAttribute:  Attribute.INTELLIGENCE, requiresTraining:  true},
    KN_NATURE:        {name: 'Kn Nature',        shortName:  'knNature',        governingAttribute:  Attribute.INTELLIGENCE, requiresTraining:  true},
    KN_NOBILITY:      {name: 'Kn Nobility',      shortName:  'knNobility',      governingAttribute:  Attribute.INTELLIGENCE, requiresTraining:  true},
    KN_PLANES:        {name: 'Kn Planes',        shortName:  'knPlanes',        governingAttribute:  Attribute.INTELLIGENCE, requiresTraining:  true},
    KN_RELIGION:      {name: 'Kn Religion',      shortName:  'knReligion',      governingAttribute:  Attribute.INTELLIGENCE, requiresTraining:  true},
    LINGUISTICS:      {name: 'Linguistics',      shortName:  'linguistics',     governingAttribute:  Attribute.INTELLIGENCE, requiresTraining:  true},
    PERCEPTION:       {name: 'Perception',       shortName:  'perception',      governingAttribute:  Attribute.WISDOM,       requiresTraining:  false},
    PERFORM:          {name: 'Perform',          shortName:  'perform',         governingAttribute:  Attribute.CHARISMA,     requiresTraining:  false},
    PROFESSION:       {name: 'Profession',       shortName:  'profession',      governingAttribute:  Attribute.WISDOM,       requiresTraining:  true},
    RIDE:             {name: 'Ride',             shortName:  'ride',            governingAttribute:  Attribute.DEXTERITY,    requiresTraining:  false},
    SENSE_MOTIVE:     {name: 'Sense Motive',     shortName:  'senseMotive',     governingAttribute:  Attribute.WISDOM,       requiresTraining:  false},
    SLEIGHT_OF_HAND:  {name: 'Sleight of Hand',  shortName:  'sleightOfHand',   governingAttribute:  Attribute.DEXTERITY,    requiresTraining:  true},
    SPELLCRAFT:       {name: 'Spellcraft',       shortName:  'spellcraft',      governingAttribute:  Attribute.INTELLIGENCE, requiresTraining:  true},
    STEALTH:          {name: 'Stealth',          shortName:  'stealth',         governingAttribute:  Attribute.DEXTERITY,    requiresTraining:  false},
    SURVIVAL:         {name: 'Survival',         shortName:  'survival',        governingAttribute:  Attribute.WISDOM,       requiresTraining:  false},
    SWIM:             {name: 'Swim',             shortName:  'swim',            governingAttribute:  Attribute.STRENGTH,     requiresTraining:  false},
    USE_MAGIC_DEVICE: {name: 'Use Magic Device', shortName:  'useMagicDevice',  governingAttribute:  Attribute.CHARISMA,     requiresTraining:  true}
};